### PR TITLE
v1 for accern data analytics documentation

### PR DESCRIPTION
**Pull request by tvskart**
initial documentation for accern analytics details.. stored in data_analytics dir for now.

### CODE REVIEW

**Review by CarlosEspejo — COMMENTED** [review]
Can you provide a screenshot in your PR of what the changes look like.

**Comment by tvskart** [comment]
screen shot 2017-02-15 at 1 18 24 pm

Adding my content under a separate tab. Can modify later.

**Comment by tvskart** [comment]
screen shot 2017-02-15 at 1 19 57 pm

empty markdown files to be filled.

**Comment by CarlosEspejo** [comment]
@anshulvp Is "Accern API Response" the right title?

**Comment by tvskart** [comment]
@CarlosEspejo @anshulvp imo, this is just first iteration. there will be many changes, especially on titles, structures, content.. I was hoping for like a dev sandbox url where i can see the changes and share with others. Not deployed to prod directly especially if its already live..

**Comment by CarlosEspejo** [comment]
@tvskart Your sandbox is when you run it locally

**Comment by tvskart** [comment]
docs2
docs1

some other changes are linking to sections, font style is bestbuy's font (looks better when lots of content)..

**Comment by CarlosEspejo** [comment]
Looks good to me 👍 
@anshulvp what do you think?

**Review by CarlosEspejo — APPROVED** [review]

**Pull request merged**
